/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    auth: typeof import('./layouts/auth.vue')['default']
    header: typeof import('./components/header.vue')['default']
    Header: typeof import('./components/header.vue')['default']
    home: typeof import('./layouts/home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Try: typeof import('./components/try.vue')['default']
  }
}
